#!/usr/bin/env python3
"""Plot backend decode/prefill throughput and vision encoder time."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


BACKENDS = ("xnnpack", "vulkan", "qnn")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot decode/prefill tokens/sec and vision encode time by backend."
    )
    parser.add_argument(
        "--runtime-csv",
        type=Path,
        default=Path(__file__).resolve().parent / "backend_runtime_by_seq.csv",
        help="Runtime summary CSV generated by plot_backend_runtime_by_seq.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent / "backend_decode_throughput_by_seq.png",
        help="Output PNG path.",
    )
    parser.add_argument(
        "--csv-output",
        type=Path,
        default=Path(__file__).resolve().parent / "backend_decode_throughput_by_seq.csv",
        help="Output throughput summary CSV path.",
    )
    return parser.parse_args()


def throughput(tokens: int, phase_ms: float) -> float:
    return tokens / (phase_ms / 1000.0) if phase_ms > 0 else 0.0


def read_runtime_rows(path: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            decode_ms = float(row["decode_ms"])
            decode_tokens = int(row["decode_tokens"])
            prefill_ms = float(row["prefill_ms"])
            prefill_tokens = int(row["prefill_tokens"])
            vision_ms = float(row["vision_ms"])
            rows.append(
                {
                    "backend": row["backend"],
                    "seq_len": int(row["seq_len"]),
                    "artifact": row["artifact"],
                    "prefill_tokens": prefill_tokens,
                    "prefill_ms": prefill_ms,
                    "prefill_tokens_per_s": throughput(prefill_tokens, prefill_ms),
                    "decode_tokens": decode_tokens,
                    "decode_ms": decode_ms,
                    "decode_tokens_per_s": throughput(decode_tokens, decode_ms),
                    "vision_ms": vision_ms,
                    "vision_s": vision_ms / 1000.0,
                }
            )
    return sorted(rows, key=lambda row: (str(row["backend"]), int(row["seq_len"])))


def write_summary_csv(rows: list[dict[str, object]], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "backend",
        "seq_len",
        "artifact",
        "prefill_tokens",
        "prefill_ms",
        "prefill_tokens_per_s",
        "decode_tokens",
        "decode_ms",
        "decode_tokens_per_s",
        "vision_ms",
        "vision_s",
    ]
    with output.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def plot_line(
    rows: list[dict[str, object]],
    value_key: str,
    title: str,
    ylabel: str,
    output: Path,
    value_format: str = "{:.1f}",
) -> None:
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(8.8, 5.2))
    colors = {"xnnpack": "tab:blue", "vulkan": "tab:orange", "qnn": "tab:green"}
    for backend in BACKENDS:
        backend_rows = [row for row in rows if row["backend"] == backend]
        if not backend_rows:
            continue
        seq_lens = [int(row["seq_len"]) for row in backend_rows]
        values = [float(row[value_key]) for row in backend_rows]
        ax.plot(
            seq_lens,
            values,
            marker="o",
            linewidth=2.2,
            label=backend.upper(),
            color=colors[backend],
        )
        for seq_len, value in zip(seq_lens, values):
            ax.text(
                seq_len,
                value,
                value_format.format(value),
                ha="center",
                va="bottom",
                fontsize=8,
            )

    ax.set_title(title)
    ax.set_xlabel("Sequence Length")
    ax.set_ylabel(ylabel)
    ax.set_xticks([512, 1024, 2048, 4096, 8192])
    ax.grid(True, alpha=0.3)
    ax.legend()
    fig.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=180)
    plt.close(fig)


def main() -> int:
    args = parse_args()
    rows = read_runtime_rows(args.runtime_csv)
    if not rows:
        raise SystemExit("No runtime rows found.")
    write_summary_csv(rows, args.csv_output)
    output_dir = args.output.parent
    plot_line(
        rows,
        "decode_tokens_per_s",
        "Decode Throughput by Backend and Sequence Length",
        "Decode Throughput (tokens/s)",
        args.output,
    )
    plot_line(
        rows,
        "prefill_tokens_per_s",
        "Prefill Throughput by Backend and Sequence Length",
        "Prefill Throughput (tokens/s)",
        output_dir / "backend_prefill_throughput_by_seq.png",
    )
    plot_line(
        rows,
        "vision_s",
        "Vision Encoder Time by Backend and Sequence Length",
        "Vision Encoder Time (s)",
        output_dir / "backend_vision_encode_time_by_seq.png",
        value_format="{:.2f}",
    )
    print(f"Wrote {args.csv_output}")
    print(f"Wrote {args.output}")
    print(f"Wrote {output_dir / 'backend_prefill_throughput_by_seq.png'}")
    print(f"Wrote {output_dir / 'backend_vision_encode_time_by_seq.png'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
