load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_library,
    name = "model",
    srcs = [
        "__init__.py",
        "model.py",
        "export_xnnpack.py",
    ],
    deps = [
        "//caffe2:torch",
        "//executorch/backends/xnnpack/partition:xnnpack_partitioner",
        "//executorch/extension/export_util:export_util",
        "//executorch/examples/qualcomm/oss_scripts/llama:encoder",
        "//executorch/examples/qualcomm/oss_scripts/llama:static_llama",
        "fbsource//third-party/pypi/transformers:transformers",
    ],
    visibility = ["PUBLIC"],
)
